name: Build and deploy Node.js app to Azure Web App - webapp-Safenotes

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: "${{ github.ref_name }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        working-directory: safenotes-backend
        run: |
          npm ci
          npm run build --if-present
          # Créer les dossiers nécessaires
          mkdir -p public/uploads
          mkdir -p files/uploads
          # Créer un fichier test pour vérifier que les dossiers sont correctement déployés
          echo "test file" > public/uploads/test.txt
          echo "test file" > files/uploads/test.txt

      - name: Deploy to Azure Web App using publish profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'colti-bayer-app-production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: safenotes-backend
